name: sentry-release

on: push

jobs:
    check-diff:
      name: check outcode
      runs-on: ubuntu-18.04
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
           
        - name: Create Release Sentry
        - uses: actions/checkout@v2
        - uses: getsentry/action-release@v1
          env:
            SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
            SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
      
        - name: install requirements
          run: pip install -r requirements.txt

        - name: run python
          run: python sameold.py
